<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="P04284" name="testCases.api.ui_api_tests.TestEirPAYGAcquisitionsApiTelesalesTEMP" tests="3" failures="1" timestamp="2021-10-04T14:49:40 BST" time="8.919" errors="0">
  <testcase name="testPostOfferToCart" time="0.312" classname="testCases.api.ui_api_tests.TestEirPAYGAcquisitionsApiTelesalesTEMP">
    <failure type="java.lang.AssertionError" message="expected:&lt;200&gt; but was:&lt;403&gt;">
      <![CDATA[java.lang.AssertionError: expected:<200> but was:<403>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at testCases.api.ui_api_tests.TestEirPAYGAcquisitionsApiTelesalesTEMP.testPostOfferToCart(TestEirPAYGAcquisitionsApiTelesalesTEMP.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testPostOfferToCart -->
  <testcase name="testLogin" time="7.760" classname="testCases.api.ui_api_tests.TestEirPAYGAcquisitionsApiTelesalesTEMP"/>
  <testcase name="testCreateTelesalesProspect" time="0.847" classname="testCases.api.ui_api_tests.TestEirPAYGAcquisitionsApiTelesalesTEMP"/>
</testsuite> <!-- testCases.api.ui_api_tests.TestEirPAYGAcquisitionsApiTelesalesTEMP -->
